# Generated by Django 5.2.7 on 2025-11-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penguin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
            ],
            options={
                'verbose_name': 'Penguin',
                'verbose_name_plural': 'Penguins',
            },
        ),
    ]
